# list dict set tuple

In [91]:
l = ["1", "2", "3"]
for index, element in enumerate(l):
    print("index is %d" % index)

index is 0
index is 1
index is 2


In [92]:
# dict comprehensions
l = [1,2,3,4,5]
dic = {x : x**2 for x in l if x!=3}
print(dic)

{1: 1, 2: 4, 4: 16, 5: 25}


In [94]:
# set comprehensions
l = [1,2,3,4,5,1,2,3,4,5]
s = {i for i in l}
print(s)

{1, 2, 3, 4, 5}


In [114]:
# tuple
l = [1,2,3,4,5]
t1 = (i for i in l)
t2 = tuple(l)
print(type(t1))
print(type(t2))
print(t2)
print(t2[0])

<class 'generator'>
<class 'tuple'>
(1, 2, 3, 4, 5)
1


In [104]:
# tuple as dict key
{(x,x+1):x for x in range(5)}

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4}

In [112]:
# tuple as element of set
t = {(x,x+1) for x in range(5)}
print(t)

{(0, 1), (3, 4), (2, 3), (1, 2), (4, 5)}


----------

# numpy

In [115]:
import numpy as np

In [116]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [121]:
# indexing [0,0] and [1,1] in array
print(a[[0,1],[0,1]])
# indexing [0,1] and [0,1] in array
# same element for twice
print(a[[0,0],[1,1]])

[1 5]
[2 2]


In [123]:
zeros = np.zeros_like(a)
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [124]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [125]:
x

array([0, 1, 2, 3])

In [126]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [127]:
y

array([ 1.,  1.,  1.,  1.,  1.])

In [128]:
z

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [129]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [130]:
# 广播
xx + y

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.]])