In [1]:
import numpy as np
# import xrange

In [2]:
# 计算乘积
help(np.prod)

Help on function prod in module numpy.core.fromnumeric:

prod(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Return the product of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a product is performed.  The default,
        axis=None, will calculate the product of all the elements in the
        input array. If axis is negative it counts from the last to the
        first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a product is performed on all of the
        axes specified in the tuple instead of a single axis or all the
        axes as before.
    dtype : dtype, optional
        The type of the returned array, as well as of the accumulator in
        which the elements are multiplied.  The dtype of `a` is used by
        default unless `a` has an integer dtype of les

In [3]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

In [6]:
print(x.shape)
print(w.shape)
print(b.shape)

(2, 4, 5, 6)
(120, 3)
(3,)


In [7]:
x.shape[0]

2

In [10]:
z = w + b

In [12]:
z.shape

(120, 3)

In [20]:
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
y = np.mean(x, axis=1)

In [21]:
y

array([ 1.,  2.,  3.])

In [22]:
for i in range(3):
    print(i)

0
1
2


In [2]:
g = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [3]:
g * (g > 1)

array([[0, 2, 3],
       [0, 2, 3],
       [0, 2, 3]])

In [50]:
g

array([[1, 3, 3],
       [1, 3, 3],
       [1, 3, 3]])

In [56]:
x = g>1

In [57]:
x

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]], dtype=bool)

In [59]:
g[x] = 0

In [60]:
g

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [61]:
x = np.array([-1,0,1])
y = np.array([1,2,3])

In [62]:
y[x>-1] = 0

In [63]:
y

array([1, 0, 0])

In [16]:
g1 = np.array([[1,2,3],[1,2,3],[1,2,3]])
g2 = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [6]:
dw = 0
for i in range(3):
    dout_row = g1[i, :].reshape(1, -1)
    x_column = g2[i, :].reshape(-1, 1)
    dw += np.dot(x_column, dout_row)

In [7]:
dw

array([[ 3,  6,  9],
       [ 6, 12, 18],
       [ 9, 18, 27]])

In [16]:
np.dot(g1.T, g2)

array([[ 3,  6,  9],
       [ 6, 12, 18],
       [ 9, 18, 27]])

In [17]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = [] 
z.append(x)
z.append(y)
print(z)
np.hstack(z)

[array([1, 2, 3]), array([4, 5, 6])]


array([1, 2, 3, 4, 5, 6])

In [18]:
print(5//3)

1


In [7]:
x = None

In [12]:
if x is None:
    x = 3
else:
    x +=3

In [13]:
x

6

In [20]:
z = np.mean(g1,axis=0)

In [23]:
z

array([ 1.,  2.,  3.])

In [25]:
g = np.array([[1,1,1],[2,2,2],[3,3,3]])
h = g - z

In [26]:
h

array([[ 0., -1., -2.],
       [ 1.,  0., -1.],
       [ 2.,  1.,  0.]])

In [27]:
h**2

array([[ 0.,  1.,  4.],
       [ 1.,  0.,  1.],
       [ 4.,  1.,  0.]])

In [30]:
x = np.array([-1,0,1])
np.var(x)

0.66666666666666663

In [32]:
np.sum(x)

0

In [38]:
g1 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
x = np.array([1,1,1,1])

In [39]:
g1 * x

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [13]:
x = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
dout = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [3]:
dx = (x >= 0) * dout

In [4]:
dx

array([[0, 2, 3],
       [0, 2, 3],
       [0, 2, 3]])

In [5]:
dx = dout
dx[x < 0] = 0

In [6]:
dx

array([[0, 2, 3],
       [0, 2, 3],
       [0, 2, 3]])

In [14]:
out1 = x * (x >= 0)

In [15]:
x

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [16]:
out2 = x
out2[x < 0] = 0

In [17]:
x

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [18]:
out2

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [19]:
a1 = 1
a2 = a1
a2 = 2

In [4]:
g = np.array([[1,1,1],[2,2,2],[3,3,3]])
np.pad(g, (2,2), 'constant', constant_values=0)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0],
       [0, 0, 2, 2, 2, 0, 0],
       [0, 0, 3, 3, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.sum(g)

18

In [5]:
gg = np.array([g,g,g,g])

In [7]:
gg.shape

(4, 3, 3)

In [15]:
np.pad(gg, ((0,0),(2,2),(2,2)), 'constant', constant_values=0)

array([[[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 0, 0],
        [0, 0, 2, 2, 2, 0, 0],
        [0, 0, 3, 3, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 0, 0],
        [0, 0, 2, 2, 2, 0, 0],
        [0, 0, 3, 3, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 0, 0],
        [0, 0, 2, 2, 2, 0, 0],
        [0, 0, 3, 3, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 0, 0],
        [0, 0, 2, 2, 2, 0, 0],
        [0, 0, 3, 3, 3, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]])

In [16]:
7//3

2

In [17]:
help(np.zeros)

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

In [23]:
x = 7//3

In [24]:
x

2

In [28]:
help(np.argmax)

Help on function argmax in module numpy.core.fromnumeric:

argmax(a, axis=None, out=None)
    Returns the indices of the maximum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.
    
    See Also
    --------
    ndarray.argmax, argmin
    amax : The maximum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.
    
    Notes
    -----
    In case of multiple occurrences of the maximum values, the indices
    corresponding to the first occurrence ar

In [30]:
np.argmax(x)

8

IndexError: index 8 is out of bounds for axis 0 with size 3

In [33]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x_ = x[1:,1:]
np.unravel_index(np.argmax(x_, axis=None), x_.shape)

(1, 1)

In [34]:
x[(1,2)]

6

In [35]:
13*13*32

5408