In [1]:
import numpy as np
# import xrange

In [2]:
# 计算乘积
help(np.prod)

Help on function prod in module numpy.core.fromnumeric:

prod(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Return the product of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a product is performed.  The default,
        axis=None, will calculate the product of all the elements in the
        input array. If axis is negative it counts from the last to the
        first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a product is performed on all of the
        axes specified in the tuple instead of a single axis or all the
        axes as before.
    dtype : dtype, optional
        The type of the returned array, as well as of the accumulator in
        which the elements are multiplied.  The dtype of `a` is used by
        default unless `a` has an integer dtype of les

In [3]:
num_inputs = 2
input_shape = (4, 5, 6)
output_dim = 3

input_size = num_inputs * np.prod(input_shape)
weight_size = output_dim * np.prod(input_shape)

x = np.linspace(-0.1, 0.5, num=input_size).reshape(num_inputs, *input_shape)
w = np.linspace(-0.2, 0.3, num=weight_size).reshape(np.prod(input_shape), output_dim)
b = np.linspace(-0.3, 0.1, num=output_dim)

In [6]:
print(x.shape)
print(w.shape)
print(b.shape)

(2, 4, 5, 6)
(120, 3)
(3,)


In [7]:
x.shape[0]

2

In [10]:
z = w + b

In [12]:
z.shape

(120, 3)

In [20]:
x = np.array([[1,1,1],[2,2,2],[3,3,3]])
y = np.mean(x, axis=1)

In [21]:
y

array([ 1.,  2.,  3.])

In [22]:
for i in range(3):
    print(i)

0
1
2


In [2]:
g = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [3]:
g * (g > 1)

array([[0, 2, 3],
       [0, 2, 3],
       [0, 2, 3]])

In [50]:
g

array([[1, 3, 3],
       [1, 3, 3],
       [1, 3, 3]])

In [56]:
x = g>1

In [57]:
x

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True]], dtype=bool)

In [59]:
g[x] = 0

In [60]:
g

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [61]:
x = np.array([-1,0,1])
y = np.array([1,2,3])

In [62]:
y[x>-1] = 0

In [63]:
y

array([1, 0, 0])

In [4]:
g1 = np.array([[1,2,3],[1,2,3],[1,2,3]])
g2 = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [6]:
dw = 0
for i in range(3):
    dout_row = g1[i, :].reshape(1, -1)
    x_column = g2[i, :].reshape(-1, 1)
    dw += np.dot(x_column, dout_row)

In [7]:
dw

array([[ 3,  6,  9],
       [ 6, 12, 18],
       [ 9, 18, 27]])

In [16]:
np.dot(g1.T, g2)

array([[ 3,  6,  9],
       [ 6, 12, 18],
       [ 9, 18, 27]])

In [17]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = [] 
z.append(x)
z.append(y)
print(z)
np.hstack(z)

[array([1, 2, 3]), array([4, 5, 6])]


array([1, 2, 3, 4, 5, 6])

In [18]:
print(5//3)

1


In [7]:
x = None

In [12]:
if x is None:
    x = 3
else:
    x +=3

In [13]:
x

6